/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KvizRouteImport } from './routes/kviz'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as PrihlaseniRouteImport } from './routes/prihlaseni'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as ResetHeslaRouteImport } from './routes/reset-hesla'
import { Route as OkruhSubjectIdRouteImport } from './routes/okruh.$subjectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KvizRoute = KvizRouteImport.update({
  id: '/kviz',
  path: '/kviz',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const PrihlaseniRoute = PrihlaseniRouteImport.update({
  id: '/prihlaseni',
  path: '/prihlaseni',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetHeslaRoute = ResetHeslaRouteImport.update({
  id: '/reset-hesla',
  path: '/reset-hesla',
  getParentRoute: () => rootRouteImport,
} as any)
const OkruhSubjectIdRoute = OkruhSubjectIdRouteImport.update({
  id: '/okruh/$subjectId',
  path: '/okruh/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kviz': typeof KvizRoute
  '/premium': typeof PremiumRoute
  '/prihlaseni': typeof PrihlaseniRoute
  '/profil': typeof ProfilRoute
  '/reset-hesla': typeof ResetHeslaRoute
  '/okruh/$subjectId': typeof OkruhSubjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kviz': typeof KvizRoute
  '/premium': typeof PremiumRoute
  '/prihlaseni': typeof PrihlaseniRoute
  '/profil': typeof ProfilRoute
  '/reset-hesla': typeof ResetHeslaRoute
  '/okruh/$subjectId': typeof OkruhSubjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kviz': typeof KvizRoute
  '/premium': typeof PremiumRoute
  '/prihlaseni': typeof PrihlaseniRoute
  '/profil': typeof ProfilRoute
  '/reset-hesla': typeof ResetHeslaRoute
  '/okruh/$subjectId': typeof OkruhSubjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kviz'
    | '/premium'
    | '/prihlaseni'
    | '/profil'
    | '/reset-hesla'
    | '/okruh/$subjectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kviz'
    | '/premium'
    | '/prihlaseni'
    | '/profil'
    | '/reset-hesla'
    | '/okruh/$subjectId'
  id:
    | '__root__'
    | '/'
    | '/kviz'
    | '/premium'
    | '/prihlaseni'
    | '/profil'
    | '/reset-hesla'
    | '/okruh/$subjectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KvizRoute: typeof KvizRoute
  PremiumRoute: typeof PremiumRoute
  PrihlaseniRoute: typeof PrihlaseniRoute
  ProfilRoute: typeof ProfilRoute
  ResetHeslaRoute: typeof ResetHeslaRoute
  OkruhSubjectIdRoute: typeof OkruhSubjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kviz': {
      id: '/kviz'
      path: '/kviz'
      fullPath: '/kviz'
      preLoaderRoute: typeof KvizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prihlaseni': {
      id: '/prihlaseni'
      path: '/prihlaseni'
      fullPath: '/prihlaseni'
      preLoaderRoute: typeof PrihlaseniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-hesla': {
      id: '/reset-hesla'
      path: '/reset-hesla'
      fullPath: '/reset-hesla'
      preLoaderRoute: typeof ResetHeslaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/okruh/$subjectId': {
      id: '/okruh/$subjectId'
      path: '/okruh/$subjectId'
      fullPath: '/okruh/$subjectId'
      preLoaderRoute: typeof OkruhSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KvizRoute: KvizRoute,
  PremiumRoute: PremiumRoute,
  PrihlaseniRoute: PrihlaseniRoute,
  ProfilRoute: ProfilRoute,
  ResetHeslaRoute: ResetHeslaRoute,
  OkruhSubjectIdRoute: OkruhSubjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
